/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/Asteroid.glb 
*/

import { useGLTF } from '@react-three/drei';

export const Asteroid = (props) => {
    const { nodes, materials } = useGLTF('/models/planets/Asteroid.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Asteroid_Icosphere.geometry}
                material={materials.Asteroid}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/Asteroid.glb');
