/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/JupOne.glb 
*/

import { useGLTF } from '@react-three/drei';

export const JupiterOne = ({ ...props }) => {
    const { nodes, materials } = useGLTF('/models/planets/JupOne.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Jupiter_Sphere.geometry}
                material={materials['Material.005']}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/JupOne.glb');
