/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/Mars.glb 
*/

import { useGLTF } from '@react-three/drei';

export const Mars = (props) => {
    const { nodes, materials } = useGLTF('/models/planets/Mars.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.mesh646701568.geometry}
                material={materials.mat14}
            />
            <mesh
                geometry={nodes.mesh646701568_1.geometry}
                material={materials.mat20}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/Mars.glb');
