/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/Moon.glb 
*/

import { useGLTF } from '@react-three/drei';

export const Moon = (props) => {
    const { nodes, materials } = useGLTF('/models/planets/Moon.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.moon.geometry}
                material={materials['moon.002']}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/Moon.glb');
