/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/Neptune.glb 
*/

import { useGLTF } from '@react-three/drei';

export const Neptune = (props) => {
    const { nodes, materials } = useGLTF('/models/planets/Neptune.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.GeoSphere001_1.geometry}
                material={materials['05___Default']}
            />
            <mesh
                geometry={nodes.GeoSphere001_1_1.geometry}
                material={materials['04___Default']}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/Neptune.glb');
