/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/PlanOne.glb 
*/

import { useGLTF } from '@react-three/drei';

export const PlanetOne = (props) => {
    const { nodes, materials } = useGLTF('/models/planets/PlanOne.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Planet_11.geometry}
                material={materials.Atlas}
                scale={100}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/PlanOne.glb');
