/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/planets/PlanetThree.glb 
*/

import { useGLTF } from '@react-three/drei';

export const PlanetThree = (props) => {
    const { nodes, materials } = useGLTF('/models/planets/PlanetThree.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes['Node-Mesh'].geometry}
                material={materials.PlanetsB_mat}
            />
            <mesh
                geometry={nodes['Node-Mesh_1'].geometry}
                material={materials.PlanetsA_mat}
            />
        </group>
    );
};

useGLTF.preload('/models/planets/PlanetThree.glb');
